config/routes.rb
SeoTool::Application.routes.draw do
  resources :subnets

  resources :domains

  resources :links

  resources :urls

  resources :statuses

  resources :sites

  root 'welcome#index'

  get 'oauth2callback' => 'application#oauth2callback'
  get 'sign_out' => 'application#sign_out'
  get 'stats' => 'stats#index'

  

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to statuses_url, notice: 'Status was successfully created.' }
        format.json { render action: 'show', status: :created, location: @status }
      else
        format.html { render action: 'new' }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to statuses_url, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:name, :style)
    end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_form.html.erb
<%= form_for(@status) do |f| %>
    <div class="panel panel-default">
      <div class="panel-body">
          <% if @status.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

              <ul>
              <% @status.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="field">
            <%= f.label :name %><br>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="field">
            <%= f.label :style %><br>
            <%= f.select(:style, [
                ['Default', 'btn-default'],
                ['Primary', 'btn-primary'],
                ['Success', 'btn-success'],
                ['Info', 'btn-info'],
                ['Warning', 'btn-warning'],
                ['Danger', 'btn-danger'],
                ['Link', 'btn-link'] ], {}, { :class => 'form-control' }) %>
          </div>
      </div>
      <div class="panel-footer">
        <%= f.submit class: 'btn pull-right btn-primary' %>
      </div>
    </div>
<% end %>

app/views/statuses/edit.html.erb
<div class="page-header">
  <h1>Show<small> ( <%= link_to @status, edit_url_path(@status) %> ) </small></h1>
</div>

<ol class="breadcrumb">
  <li><a href="/">Home</a></li>
  <li><%= link_to 'Status', statuses_path %></li>
  <li class="active"><%= @status %></li>
</ol>

<%= render 'form' %>

app/views/statuses/index.html.erb
<div class="page-header">
  <h1>Listing status <small> ( <%= link_to 'Create Status', new_status_path %> ) </small></h1>
</div>

<ol class="breadcrumb">
  <li><a href="/">Home</a></li>
  <li class="active">Status</li>
</ol>

<table class='table table-striped table-hover'>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @statuses.each do |status| %>
      <tr>
        <td><%= status.name %></td>
        <td width=30><%= link_to ' ', edit_status_path(status), class: 'btn btn-default btn-sm glyphicon glyphicon-edit' %></td>
        <td width=30><%= link_to ' ', status, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm glyphicon glyphicon-remove' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/statuses/new.html.erb
<div class="page-header">
  <h1>New status</h1>
</div>

<ol class="breadcrumb">
  <li><a href="/">Home</a></li>
  <li><%= link_to 'Urls', urls_path %></li>
  <li class="active">New status</li>
</ol>

<%= render 'form' %>

app/views/statuses/show.html.erb
<div class="page-header">
  <h1>Show<small> ( <%= link_to @status, edit_url_path(@status) %> ) </small></h1>
</div>

<ol class="breadcrumb">
  <li><a href="/">Home</a></li>
  <li><%= link_to 'Status', statuses_path %></li>
  <li class="active"><%= @status %></li>
</ol>
<p>
  <strong>Name:</strong>
  <%= @status.name %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>