config/routes.rb
SeoTool::Application.routes.draw do
  resources :subnets

  resources :domains

  resources :links

  resources :urls

  resources :statuses

  resources :sites

  root 'welcome#index'

  get 'oauth2callback' => 'application#oauth2callback'
  get 'sign_out' => 'application#sign_out'
  get 'stats' => 'stats#index'

  

end

app/models/url.rb
require 'addressable/uri'
require 'domainatrix'

class Url < ActiveRecord::Base
  belongs_to :domain
  has_many :links
  has_many :stats

  validates_uniqueness_of :url

  default_scope { order(id: :asc) }

  paginates_per 50

  def original_subdomain
    return '' if invalid_url?
    url = "http://#{self.url}" if URI.parse(self.url).scheme.nil?
    return URI.parse(self.url).host.downcase
  rescue Exception
    return ''
  end

  def original_domain
    return '' if invalid_url?
    uri = Domainatrix.parse(url)
    "#{uri.domain}.#{uri.public_suffix}"
  rescue Exception
    return ''
  end

  def invalid_url?
    return true if url.empty?
    return true if url.starts_with?('/') or url.starts_with?('#')
    return true unless url=~ URI::regexp
    return true if url.starts_with?('mailto:')
    return true if url.starts_with?('javascript:')
  end

end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :set_url, only: [:show, :edit, :update, :destroy]

  # GET /urls
  # GET /urls.json
  def index

    search_term = params[:search].to_s.strip
    if search_term
      @urls = Url.where('url like ?', "%#{search_term}%").page params[:page]
    else
      @urls = Url.all.page params[:page]
    end
  end

  # GET /urls/1
  # GET /urls/1.json
  def show
    @sites = Site.all
  end

  # GET /urls/new
  def new
    @url = Url.new
  end

  # GET /urls/1/edit
  def edit
  end

  # POST /urls
  # POST /urls.json
  def create
    @url = Url.new(url_params)

    respond_to do |format|
      if @url.save
        format.html { redirect_to @url, notice: 'Url was successfully created.' }
        format.json { render action: 'show', status: :created, location: @url }
      else
        format.html { render action: 'new' }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /urls/1
  # PATCH/PUT /urls/1.json
  def update
    respond_to do |format|
      if @url.update(url_params)
        format.html { redirect_to @url, notice: 'Url was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /urls/1
  # DELETE /urls/1.json
  def destroy
    @url.destroy
    respond_to do |format|
      format.html { redirect_to urls_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_url
    @url = Url.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def url_params
    params.require(:url).permit(:status_id, :url)
  end
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/urls/_form.html.erb
<%= form_for(@url) do |f| %>
    <div class="panel panel-default">
      <div class="panel-body">
        <% if @url.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@url.errors.count, "error") %> prohibited this url from being saved:</h2>

              <ul>
                <% @url.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <div class="field">
          <%= f.label :url %><br>
          <%= f.text_field :url, class: 'form-control' %>
        </div>
      </div>
      <div class="panel-footer">
        <%= f.submit class: 'btn pull-right btn-primary' %>
      </div>
    </div>

<% end %>

app/views/urls/edit.html.erb
<div class="page-header">
  <h1>Edit<small> ( <%= link_to @url.url, edit_url_path(@url) %> ) </small></h1>
</div>

<ol class="breadcrumb">
  <li><a href="/">Home</a></li>
  <li><%= link_to 'Urls', urls_path %></li>
  <li class="active"><%= @url.url %></li>
</ol>

<%= render 'form' %>

app/views/urls/index.html.erb
<div class="page-header">
  <h1>Listing urls <small> ( <%= link_to 'Create Url', new_url_path %> ) </small></h1>
  <div class='pull-right' style='margin-top:-30px'>
      <%= form_tag urls_path, method: 'get', class: 'form-inline' do %>
        <div class="form-group"><%= text_field_tag :search, params[:search], class: 'form-control' %></div>
        <div class="form-group"><%= submit_tag "Search", :name => nil, class: 'btn' %></div>
      <% end %>
  </div>
</div>

<ol class="breadcrumb">
  <li><a href="/">Home</a></li>
  <li class="active">Urls</li>
</ol>

<table class='table table-striped table-hover'>
  <thead>
    <tr>
      <th class="col-md-5">Url</th>
      <th class="col-md-1">DA</th>
      <th class="col-md-1">PA</th>
      <th class="col-md-1">Int L</th>
      <th class="col-md-1">Ext L</th>
      <th class="col-md-2">Last Visit</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @urls.each do |url| %>
      <tr>
        <td><%= link_to url.url, url.url, target: '_blank' %></td>
        <td><%= url.domain_authority.to_i.round(2) %></td>
        <td><%= url.page_authority.to_i.round(2) %></td>
        <td><%= url.internal_links %></td>
        <td><%= url.external_links %></td>
        <td><%= url.visited_at or 'Never' %></td>
        <td width=30><%= link_to ' ', url, class: 'btn btn-default btn-sm glyphicon glyphicon-eye-open' %></td>
        <td width=30><%= link_to ' ', edit_url_path(url), class: 'btn btn-default btn-sm glyphicon glyphicon-edit' %></td>
        <td width=30><%= link_to ' ', url, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm glyphicon glyphicon-remove' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @urls %>

app/views/urls/new.html.erb
<div class="page-header">
  <h1>New url</h1>
</div>

<ol class="breadcrumb">
  <li><a href="/">Home</a></li>
  <li><%= link_to 'Urls', urls_path %></li>
  <li class="active">New url</li>
</ol>

<%= render 'form' %>

app/views/urls/show.html.erb
<p id="notice"><%= notice %></p>

<div class="page-header">
  <h1>URL Details<small> ( <%= link_to 'Edit', edit_url_path(@url) %> ) </small></h1>
</div>

<ol class="breadcrumb">
  <li><a href="/">Home</a></li>
  <li><%= link_to 'Urls', urls_path %></li>
  <li class="active">View: <%= @url.url %></li>
</ol>


<div class="row">
  <div class="col-md-8">
    <table class='table table-hover'>
      <tbody>
          <tr>
            <td>Last visit:</td>
            <td><strong><%= @url.visited_at or 'Never' %></strong></td>
          </tr>
          <tr>
            <td>Internal links:</td>
            <td><strong><%= @url.internal_links %></strong></td>
          </tr>
          <tr>
            <td>External links:</td>
            <td><strong><%= @url.external_links %></strong></td>
          </tr>
          <tr>
            <td>IP:</td>
            <td><strong><%= @url.ip %></strong></td>
          </tr>
          <tr>
            <td>Domain:</td>
            <td><strong><%= @url.domain %></strong></td>
          </tr>
          <tr>
            <td>Sub-Domain:</td>
            <td><strong><%= @url.subdomain %></strong></td>
          </tr>
          <tr>
            <td>Domain authority:</td>
            <td class="progress active progress-striped" style='text-align:right'>
              <div style='position:absolute; color:black; padding-left:5px;'><strong><%= @url.domain_authority.to_f.round(1) %></strong></div>
              <div class="progress-bar progress-bar-warning"  role="progressbar" aria-valuenow="<%= @url.domain_authority.to_i %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= @url.domain_authority.to_i %>%">
                <span class="sr-only"><%= @url.domain_authority.to_f.round(1) %></span>
              </div>
            </td>
          </tr>
          <tr>
            <td>Page authority:</td>
            <td class="progress active progress-striped" style='text-align:right'>
              <div style='position:absolute; color:black; padding-left:5px;'><strong><%= @url.page_authority.to_f.round(1) %></strong></div>
              <div class="progress-bar progress-bar-warning"  role="progressbar" aria-valuenow="<%= @url.page_authority.to_i %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= @url.page_authority.to_i %>%">
                <span class="sr-only"><%= @url.page_authority.to_f.round(1) %></span>
              </div>
            </td>
          </tr>
      </tbody>
    </table>
  </div>
  <% if @url.internal_links.to_i > 0 || @url.external_links.to_i > 0 %>
      <div class="col-md-4">
        <div id="donutchart" style="width: 100%; height: 300px;"></div>
      </div>
  <% end %>
</div>


<% @sites.each do |site| %>
    <% if @url.links.where(:site_id => site.id).length > 0 %>
        <div>
          <h3><%= site.code %><small> ( <%= site.domain %> ) </small></h3>
        </div>
        <table class='table table-striped table-hover'>
          <thead>
          <tr>
            <th>Url</th>
            <th>Anchor</th>
            <th>Affiliate</th>
            <th align='center'>Campaign</th>
            <th style='text-align:center'>Status</th>
          </tr>
          </thead>
          <tbody>
          <% @url.links.where(:site_id => site.id).each do |link| %>
              <tr>
                <td><%= link_to link.link, link.link %></td>
                <td><%= link.anchor %></td>
                <td><%= link.affiliate %></td>
                <td align='center'><%= link.campaign %></td>
                <td align='right'>
                  <% if link.status == 'link not found' %>
                      <div class="btn btn-danger"><%= link.status %></div>
                  <% else %>
                      <div class="btn btn-success"><%= link.status %></div>
                  <% end %>

                </td>
              </tr>
          <% end %>
          </tbody>
        </table>
    <% end %>
<% end %>