config/routes.rb
SeoTool::Application.routes.draw do
  resources :subnets

  resources :domains

  resources :links

  resources :urls

  resources :statuses

  resources :sites

  root 'welcome#index'

  get 'oauth2callback' => 'application#oauth2callback'
  get 'sign_out' => 'application#sign_out'
  get 'stats' => 'stats#index'

  

end

app/models/domain.rb
class Domain < ActiveRecord::Base
  belongs_to :status
  belongs_to :subnet
  has_many :urls

  after_initialize :init

  default_scope { order(links_counter: :desc) }
  paginates_per 50

  def init
    self.status ||= Status.where(name: 'Empty').first
  end

  def to_s
    url
  end

  def affiliate?
    if status.nil? || status.empty?
      if affiliates_count > minimum_affiliate_count
        true
      else
        false
      end
    elsif status.affiliate?
      true
    else
      false
    end
  end

  def count_links_not_found
    Url.joins(:links).where(domain_id: id, 'links.status' => 'link not found').count
  end

  def affiliates_count
    Url.joins(:links).where('links.affiliate' => 'yes', domain: self).count
  end

  def minimum_affiliate_count
    5
  end

end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  before_action :set_domain, only: [:show, :next, :edit, :update, :destroy, :update_urls_status]

  # GET /domains
  # GET /domains.json
  def index
    @statuses   = Status.all
    session[:all_domains] = search_domains(params).pluck(:id)
    @domains = search_domains(params).page params[:page]
  end

  # GET /domains/1
  # GET /domains/1.json
  def show
    @next_domain = nil
    if session[:all_domains] && session[:all_domains].index(params[:id].to_i)
      next_index = session[:all_domains].index(params[:id].to_i).next
      @next_domain = session[:all_domains][next_index]
    end
    @statuses = Status.all
    @urls = @domain.urls.page params[:page]
  end

  # GET /domains/new
  def new
    @domain = Domain.new
  end

  # GET /domains/1/edit
  def edit
  end

  # POST /domains
  # POST /domains.json
  def create
    @domain = Domain.new(domain_params)

    respond_to do |format|
      if @domain.save
        format.html { redirect_to @domain, notice: 'Domain was successfully created.' }
        format.json { render action: 'show', status: :created, location: @domain }
      else
        format.html { render action: 'new' }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /domains/1
  # PATCH/PUT /domains/1.json
  def update
    respond_to do |format|
      if @domain.update(domain_params)
        format.html { redirect_to @domain, notice: 'Domain was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /domains/1
  # DELETE /domains/1.json
  def destroy
    @domain.destroy

    respond_to do |format|
      format.html { redirect_to domains_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_domain
    @domain = Domain.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def domain_params
    params.require(:domain).permit(:url, :status_id)
  end

  # Search domains by term and status
  def search_domains(params)
    status_id   = params[:status_id].to_s.strip
    search_term = params[:search].to_s.strip

    if search_term
      if status_id.empty?
        Domain.where('url like ?', "%#{search_term}%")
      else
        Domain.where('url like ? AND status_id = ?', "%#{search_term}%", status_id)
      end
    else
      Domain.all
    end
  end

end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/views/domains/_domain.html.erb
        <tr>
            <td><%= domain.url %></td>
            <td class='<%= domain.status.style.gsub('btn-', '') if domain.status %>'><%= domain.status %></td>
            <td><%= domain.links_counter %></td>
            <td width=30><%= link_to ' ', domain, class: 'btn btn-default btn-sm glyphicon glyphicon-eye-open' %></td>
            <td width=30><%= link_to ' ', edit_domain_path(domain), class: 'btn btn-default btn-sm glyphicon glyphicon-edit' %></td>
            <td width=30><%= link_to ' ', domain, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm glyphicon glyphicon-remove' %></td>
        </tr>

app/views/domains/_form.html.erb
<%= form_for(@domain) do |f| %>
    <div class="panel panel-default">
        <div class="panel-body">
            <% if @domain.errors.any? %>
                <div id="error_explanation">
                    <h2><%= pluralize(@domain.errors.count, "error") %> prohibited this site from being saved:</h2>

                    <ul>
                        <% @domain.errors.full_messages.each do |msg| %>
                            <li><%= msg %></li>
                        <% end %>
                    </ul>
                </div>
            <% end %>

            <div class="field">
                <%= f.label :url %><br>
                <%= f.text_field :url, class: 'form-control' %>
            </div>
            <div class="field">
                <%= f.label :status %><br>
                <%= collection_select(:url, :status_id, Status.all, :id, :name, {}, { class: 'form-control' }) %>
            </div>

        </div>
        <div class="panel-footer">
            <%= f.submit class: 'btn pull-right btn-primary' %>
        </div>
    </div>

<% end %>

app/views/domains/edit.html.erb
<div class="page-header">
    <h1>Editing domain</h1>
</div>

<ol class="breadcrumb">
    <li><a href="/">Home</a></li>
    <li><%= link_to 'Domains', domains_path %></li>
    <li class="active"><%= @domain.url %></li>
</ol>
<%= render 'form' %>

app/views/domains/index.html.erb
<div class="page-header">
    <h1>Listing domains <small> ( <%= link_to 'Create domain', new_domain_path %> ) </small></h1>
    <div class='pull-right' style='margin-top:-30px'>
        <%= form_tag domains_path, method: 'get', class: 'form-inline' do %>
            <div class="form-group"><%= text_field_tag :search, params[:search], class: 'form-control' %></div>
            <div class="form-group">
              <%= select_tag('status_id', content_tag(:option, 'Select one...', :value => "") + options_from_collection_for_select(@statuses, 'id', 'name', params[:status_id].to_i), { :class => 'form-control' }) %>
            </div>
            <div class="form-group"><%= submit_tag "Search", :name => nil, class: 'btn' %></div>
        <% end %>
    </div>
</div>

<ol class="breadcrumb">
    <li><a href="/">Home</a></li>
    <li class="active">Domains</li>
</ol>

<table class='table table-striped table-hover'>
    <thead>
    <tr>
        <th class="col-md-9">Url</th>
        <th>Status</th>
        <th>Links</th>
        <th></th>
        <th></th>
        <th></th>
    </tr>
    </thead>

    <tbody>
        <% @domains.each do |domain| %>
            <tr>
              <td><%= domain.url %></td>
              <td class='<%= domain.status.style.gsub('btn-', '') if domain.status %>'><%= domain.status %></td>
              <td><%= domain.links_counter %></td>
              <td width=30><%= link_to ' ', domain, class: 'btn btn-default btn-sm glyphicon glyphicon-eye-open' %></td>
              <td width=30><%= link_to ' ', edit_domain_path(domain), class: 'btn btn-default btn-sm glyphicon glyphicon-edit' %></td>
              <td width=30><%= link_to ' ', domain, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm glyphicon glyphicon-remove' %></td>
            </tr>
        <% end %>
    </tbody>
</table>

<%= paginate @domains %>

app/views/domains/new.html.erb
<div class="page-header">
    <h1>New domain</h1>
</div>

<ol class="breadcrumb">
    <li><a href="/">Home</a></li>
    <li><%= link_to 'Domain', domains_path %></li>
    <li class="active">New domain</li>
</ol>

<%= render 'form' %>

app/views/domains/show.html.erb
<div class="page-header">
    <h1>View domain
        <small> ( <%= link_to @domain.url, edit_domain_path(@domain) %> )</small>
    </h1>
</div>


<ol class="breadcrumb">
    <li><a href="/">Home</a></li>
    <li><%= link_to 'Domains', domains_path %></li>
    <li class="active"><%= @domain %></li>
    <% if @next_domain %>
    <li class='pull-right'><a href='<%= url_for domain_url(@next_domain) %>'>Next &rsaquo;</a></li>
    <% end %>
</ol>

<p>
<div class="panel-footer">
  <% if @domain.status %>
  <div class='pull-left'>
    <h4><small>Current status :</small> <span class='label <%= @domain.status.style.gsub('btn-', 'label-') %>'><%= @domain.status.name.capitalize %></span></h4>
  </div>
  <% end %>
  <% @statuses.each do |status| %>
      <%= form_for @domain, :method => "put" do |f| %>
          <%= f.hidden_field :status_id, :value => status.id %>
          <%= f.submit status.name.capitalize, class: "btn pull-right #{status.style}" %>
      <% end %>
  <% end %>
</div>

<table class='table table-striped table-hover'>
    <thead>
    <tr>
        <th>Url</th>
        <th width=150>Links</th>
        <th></th>
        <th></th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    <% @urls.each do |url| %>
        <tr>
            <td><%= link_to url.url, url.url %></td>
            <td><%= url.links.count %></td>
            <td width=30><%= link_to ' ', url, class: 'btn btn-default btn-sm glyphicon glyphicon-eye-open' %></td>
            <td width=30><%= link_to ' ', edit_url_path(url), class: 'btn btn-default btn-sm glyphicon glyphicon-edit' %></td>
            <td width=30><%= link_to ' ', url, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger btn-sm glyphicon glyphicon-remove' %></td>
        </tr>
    <% end %>
    </tbody>
</table>
</p>

<%= paginate @urls %>

app/views/domains/status.html.erb
<div class="page-header">
    <h1>Update urls's status
        <small>(<%= @domain.url %>)</small>
    </h1>
</div>

<ol class="breadcrumb">
    <li><a href="/">Home</a></li>
    <li><%= link_to 'Domains', domains_path %></li>
    <li class="active"><%= @domain.url %></li>
</ol>

<%= form_for(@domain, :url => '') do |f| %>
    <div class="field">
        <%= f.label :status %><br>
        <%= collection_select(:url, :status_id, Status.all, :id, :name, {}, {class: 'form-control'}) %>
    </div>
    <div class="panel-footer">
        <%= f.submit class: 'btn pull-right btn-primary' %>
    </div>

<% end %>